server:
  port: 5000
spring:
  application:
    name: atxiaoyan-crowd-project
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 192.168.163.140
    password: 201314
    session:
      store-type: redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
aliyun:
  oss:
    access-key-id: LTAI5tJMLorYFzNWSmgWiwBR
    access-key-secret: kXco6m3piBsB7K1kGEEnNZ8bWt9lGS
    bucket-domain: http://atxiaoyan.oss-cn-hangzhou.aliyuncs.com
    bucket-name: atxiaoyan
    end-point: http://oss-cn-hangzhou.aliyuncs.com